import os

dirs = [
    "frontend/src/components/assistant",
    "frontend/src/components/chat",
    "frontend/src/components/sidebar",
    "frontend/src/components/settings",
    "frontend/src/components/common",
    "frontend/src/pages",
    "frontend/src/hooks",
    "frontend/src/services",
    "frontend/src/store",
    "frontend/src/layouts",
    "frontend/src/styles",
    "frontend/src/assets/avatars",
    "frontend/src/assets/icons",
    "frontend/src/assets/sounds",
    "frontend/src/assets/wallpapers",
    "frontend/src/utils",
    "frontend/public",
    "frontend/src-tauri/src",
    "frontend/src-tauri/icons",
    "backend/api/routes",
    "backend/api/websocket",
    "backend/brain/gemini",
    "backend/brain/personality",
    "backend/brain/memory",
    "backend/brain/reasoning",
    "backend/tools/desktop",
    "backend/tools/browser",
    "backend/tools/vscode",
    "backend/tools/filesystem",
    "backend/tools/system",
    "backend/voice/input",
    "backend/voice/output",
    "backend/voice/realtime",
    "backend/vision/capture",
    "backend/vision/ocr",
    "backend/vision/analysis",
    "backend/database",
    "backend/config",
    "backend/utils",
    "backend/data/chats",
    "backend/data/screenshots",
    "backend/data/cache",
    "backend/tests",
    "shared/types",
    "shared/events",
    "shared/prompts",
    "shared/schemas",
    "docs",
    "scripts"
]

files = {
    "frontend/src/components/assistant/Avatar.tsx": "",
    "frontend/src/components/assistant/VoiceOrb.tsx": "",
    "frontend/src/components/assistant/EmotionIndicator.tsx": "",
    "frontend/src/components/assistant/RelationshipMeter.tsx": "",
    "frontend/src/components/assistant/FloatingAssistant.tsx": "",
    "frontend/src/components/assistant/StatusRing.tsx": "",
    "frontend/src/components/chat/ChatWindow.tsx": "",
    "frontend/src/components/chat/ChatBubble.tsx": "",
    "frontend/src/components/chat/MessageInput.tsx": "",
    "frontend/src/components/chat/TypingIndicator.tsx": "",
    "frontend/src/components/chat/VoiceButton.tsx": "",
    "frontend/src/components/sidebar/Sidebar.tsx": "",
    "frontend/src/components/sidebar/MemoryCard.tsx": "",
    "frontend/src/components/sidebar/MoodCard.tsx": "",
    "frontend/src/components/sidebar/ActivityCard.tsx": "",
    "frontend/src/components/settings/VoiceSettings.tsx": "",
    "frontend/src/components/settings/PersonalitySettings.tsx": "",
    "frontend/src/components/settings/ThemeSettings.tsx": "",
    "frontend/src/components/settings/AutomationSettings.tsx": "",
    "frontend/src/components/common/Button.tsx": "",
    "frontend/src/components/common/Modal.tsx": "",
    "frontend/src/components/common/Loader.tsx": "",
    "frontend/src/components/common/GlassCard.tsx": "",
    "frontend/src/pages/Home.tsx": "",
    "frontend/src/pages/Memories.tsx": "",
    "frontend/src/pages/Settings.tsx": "",
    "frontend/src/pages/Automation.tsx": "",
    "frontend/src/pages/Debug.tsx": "",
    "frontend/src/hooks/useVoice.ts": "",
    "frontend/src/hooks/useSocket.ts": "",
    "frontend/src/hooks/useEmotion.ts": "",
    "frontend/src/hooks/useMemory.ts": "",
    "frontend/src/hooks/useAssistant.ts": "",
    "frontend/src/services/api.ts": "",
    "frontend/src/services/websocket.ts": "",
    "frontend/src/services/assistant.ts": "",
    "frontend/src/services/voice.ts": "",
    "frontend/src/services/automation.ts": "",
    "frontend/src/store/assistantStore.ts": "",
    "frontend/src/store/chatStore.ts": "",
    "frontend/src/store/emotionStore.ts": "",
    "frontend/src/store/voiceStore.ts": "",
    "frontend/src/store/settingsStore.ts": "",
    "frontend/src/layouts/MainLayout.tsx": "",
    "frontend/src/layouts/FloatingLayout.tsx": "",
    "frontend/src/styles/globals.css": "",
    "frontend/src/styles/animations.css": "",
    "frontend/src/styles/themes.css": "",
    "frontend/src/utils/helpers.ts": "",
    "frontend/src/utils/constants.ts": "",
    "frontend/src/utils/animations.ts": "",
    "frontend/src/utils/formatters.ts": "",
    "frontend/src/App.tsx": "",
    "frontend/src/main.tsx": "",
    "frontend/src/routes.tsx": "",
    "frontend/src-tauri/src/main.rs": "",
    "frontend/src-tauri/tauri.conf.json": "{}",
    "frontend/src-tauri/Cargo.toml": "",
    "frontend/package.json": "{}",
    "frontend/vite.config.ts": "",
    "frontend/tailwind.config.js": "",
    "frontend/tsconfig.json": "{}",
    "frontend/postcss.config.js": "",
    
    "backend/api/routes/assistant.py": "",
    "backend/api/routes/automation.py": "",
    "backend/api/routes/memory.py": "",
    "backend/api/routes/settings.py": "",
    "backend/api/websocket/manager.py": "",
    "backend/api/websocket/events.py": "",
    "backend/api/websocket/handlers.py": "",
    "backend/api/server.py": "",
    "backend/brain/gemini/client.py": "",
    "backend/brain/gemini/live.py": "",
    "backend/brain/gemini/prompts.py": "",
    "backend/brain/gemini/planner.py": "",
    "backend/brain/gemini/function_calls.py": "",
    "backend/brain/personality/maya_personality.py": "",
    "backend/brain/personality/emotions.py": "",
    "backend/brain/personality/moods.py": "",
    "backend/brain/personality/relationship.py": "",
    "backend/brain/memory/memory_manager.py": "",
    "backend/brain/memory/conversation_memory.py": "",
    "backend/brain/memory/emotional_memory.py": "",
    "backend/brain/memory/user_profile.py": "",
    "backend/brain/reasoning/task_planner.py": "",
    "backend/brain/reasoning/action_selector.py": "",
    "backend/brain/reasoning/workflow_engine.py": "",
    "backend/tools/desktop/apps.py": "",
    "backend/tools/desktop/windows.py": "",
    "backend/tools/desktop/mouse.py": "",
    "backend/tools/desktop/keyboard.py": "",
    "backend/tools/desktop/screenshots.py": "",
    "backend/tools/browser/playwright_manager.py": "",
    "backend/tools/browser/whatsapp.py": "",
    "backend/tools/browser/youtube.py": "",
    "backend/tools/browser/google.py": "",
    "backend/tools/browser/tabs.py": "",
    "backend/tools/vscode/project_creator.py": "",
    "backend/tools/vscode/code_writer.py": "",
    "backend/tools/vscode/terminal_runner.py": "",
    "backend/tools/vscode/extensions.py": "",
    "backend/tools/filesystem/files.py": "",
    "backend/tools/filesystem/folders.py": "",
    "backend/tools/filesystem/editor.py": "",
    "backend/tools/filesystem/search.py": "",
    "backend/tools/system/audio.py": "",
    "backend/tools/system/camera.py": "",
    "backend/tools/system/clipboard.py": "",
    "backend/tools/system/notifications.py": "",
    "backend/tools/system/processes.py": "",
    "backend/voice/input/microphone.py": "",
    "backend/voice/input/vad.py": "",
    "backend/voice/input/transcriber.py": "",
    "backend/voice/input/noise_reduction.py": "",
    "backend/voice/output/elevenlabs.py": "",
    "backend/voice/output/audio_player.py": "",
    "backend/voice/output/streaming_tts.py": "",
    "backend/voice/realtime/audio_pipeline.py": "",
    "backend/voice/realtime/interruption.py": "",
    "backend/voice/realtime/streaming.py": "",
    "backend/vision/capture/screen_capture.py": "",
    "backend/vision/capture/webcam_capture.py": "",
    "backend/vision/ocr/text_detector.py": "",
    "backend/vision/ocr/parser.py": "",
    "backend/vision/analysis/ui_detector.py": "",
    "backend/vision/analysis/vision_agent.py": "",
    "backend/vision/analysis/screenshot_analyzer.py": "",
    "backend/database/connection.py": "",
    "backend/database/models.py": "",
    "backend/database/migrations.py": "",
    "backend/database/schema.sql": "",
    "backend/config/settings.py": "",
    "backend/config/secrets.py": "",
    "backend/config/constants.py": "",
    "backend/utils/logger.py": "",
    "backend/utils/decorators.py": "",
    "backend/utils/helpers.py": "",
    "backend/utils/validators.py": "",
    "backend/tests/test_voice.py": "",
    "backend/tests/test_tools.py": "",
    "backend/tests/test_memory.py": "",
    "backend/requirements.txt": "fastapi\nuvicorn[standard]\nwebsockets\nfaster-whisper\nelevenlabs\npyautogui\nplaywright\npython-dotenv\nsqlalchemy\n",
    "backend/main.py": "",
    "backend/run.py": "",
    
    "docs/architecture.md": "# Architecture\n",
    "docs/api.md": "# API Documentation\n",
    "docs/websocket.md": "# WebSocket Events\n",
    "docs/automation.md": "# Automation Capabilities\n",
    "docs/roadmap.md": "# Roadmap\n",
    "docs/setup.md": "# Setup Instructions\n",
    ".gitignore": "node_modules/\n.venv/\n__pycache__/\n.env\ndist/\nbuild/\n",
    "README.md": "# Maya AI\n",
    "start.bat": "@echo off\necho Starting Maya AI...\n",
    "start.sh": "#!/bin/bash\necho Starting Maya AI...\n"
}

for d in dirs:
    os.makedirs(d, exist_ok=True)

for f, content in files.items():
    with open(f, 'w', encoding='utf-8') as file:
        file.write(content)

print("Scaffolding completed.")
